"""Mechanical reproduction steps for drift reports (no LLM)."""

from __future__ import annotations

from pathlib import Path
from typing import Any


REPRODUCE_TEMPLATE = """# Reproduce — {page_id} ({profile})

Mechanical checklist generated by fuzzy-validator. Do not invent alternate steps.

## Setup

1. From repo root, restore the gold-master setpoint (pin the bundle used for this run):
   ```bash
   bin/fuzzy-validator setpoint restore{setpoint_flag}
   ```
2. Select the database profile:
   ```bash
   bin/ork-db use {ork_db_use}
   ```
3. Ensure the app is reachable at `{base_url}` (docker php8 stack if local).

## Page under test

| Field | Value |
|-------|-------|
| Page id | `{page_id}` |
| Profile | `{profile}` |
| URL path | `{url}` |
| Viewport | {viewport} |
| Auth | `{auth}` |

## Re-run validate

```bash
bin/fuzzy-validator validate --page {page_id} --profile {profile} --phase all{overlay_flags}
```

## Evidence in this report bundle

| Artifact | Relative path |
|----------|---------------|
| Baseline screenshot | `{baseline}` |
| Candidate screenshot | `{candidate}` |
| Annotated / diff | `{annotated}` |
| DOM diff (if any) | `{dom_diff}` |

Open `index.html` in this run directory for the classified drift inventory.
"""


def _ork_db_use(profile: str) -> str:
    if profile == "mirror":
        return "prod"
    return "dev"


def render_reproduce_md(
    *,
    page_id: str,
    profile: str,
    page: dict[str, Any] | None = None,
    defaults: dict[str, Any] | None = None,
    base_url: str = "http://localhost:19080/orkui/",
    setpoint_bundle: str | None = None,
    overlay_args: str = "",
) -> str:
    page = page or {}
    defaults = defaults or {}
    viewport = page.get("viewport") or defaults.get("viewport") or {}
    if isinstance(viewport, dict) and "width" in viewport and "height" in viewport:
        viewport_text = f"{viewport['width']}×{viewport['height']}"
    else:
        viewport_text = "registry default"
    auth = page.get("auth") or defaults.get("auth") or "none"
    url = page.get("url") or f"(see pages.json5 id={page_id})"
    setpoint_flag = f" --bundle {setpoint_bundle}" if setpoint_bundle else ""
    overlay_flags = f" {overlay_args.strip()}" if overlay_args.strip() else ""
    return REPRODUCE_TEMPLATE.format(
        page_id=page_id,
        profile=profile,
        ork_db_use=_ork_db_use(profile),
        base_url=base_url.rstrip("/") + "/",
        url=url,
        viewport=viewport_text,
        auth=auth,
        setpoint_flag=setpoint_flag,
        overlay_flags=overlay_flags,
        baseline=f"../../data/{page_id}-baseline.png",
        candidate=f"../../data/{page_id}-candidate.png",
        annotated=f"../../data/{page_id}-annotated.png",
        dom_diff=f"../../data/{page_id}-dom-diff.json",
    )


def write_reproduce_md(
    run_dir: Path,
    *,
    page_id: str,
    profile: str,
    page: dict[str, Any] | None = None,
    defaults: dict[str, Any] | None = None,
    base_url: str = "http://localhost:19080/orkui/",
    setpoint_bundle: str | None = None,
    overlay_args: str = "",
) -> Path:
    pages_dir = run_dir / "pages" / page_id
    pages_dir.mkdir(parents=True, exist_ok=True)
    content = render_reproduce_md(
        page_id=page_id,
        profile=profile,
        page=page,
        defaults=defaults,
        base_url=base_url,
        setpoint_bundle=setpoint_bundle,
        overlay_args=overlay_args,
    )
    out = pages_dir / "reproduce.md"
    out.write_text(content, encoding="utf-8")
    return out
