<!DOCTYPE html>
<html>
	<head>
		<title><?php echo (strlen($page_title)>0?"ORK 3: ":"ORK 3").ucwords($page_title); ?></title>
		<link rel="icon" href="/favicon.ico">
		<?php if ($no_index) : ?>
		<meta name="robots" content="noindex">
		<?php endif ; ?>
		<meta name=viewport content="user-scalable=no,width=device-width,minimum-scale=1" />
		<link type="text/css" href="<?=HTTP_TEMPLATE;?>default/style/orkui.css" rel="stylesheet" />
		
    	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
		<script type="text/javascript" src="<?=HTTP_TEMPLATE;?>default/script/orkui.js"></script>
		<!-- Google tag (gtag.js) -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=G-PVQCKENY0M"></script>
		<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-PVQCKENY0M');
		</script>
	</head>
	<body>
		<div id='theme_container'>

<?php
	echo $CONTROLLER_CONTENTS;
?>

		</div>

	
	<a id="simple-menu" href="#sidr">Menu</a>
	<div id='newmenu'>
	<?php if (isset($menu) && is_array($menu) && count($menu) > 0) : ?>
			<div id='navmenu'>
				<ul>
	<?php foreach ($menu as $k => $item) : ?>
					<li><a href='<?=$item["url"] ?>'><?=$item["display"] ?></a> <span class='breadcrumb-trail'><?=(isset($item['no-crumb']) || $item === end($menu))?'':'<i class="fas fa-angle-double-right"></i>'; ?></span> </li>
	<?php endforeach; ?>
				</ul>
			</div>
	<?php endif; ?>
			<div id='controls'>
				<ul>
					<li><a href='https://docs.google.com/document/d/18wsfFoyD6RXrO4FAxXjfHRTQ0Z_4mWZqzI5f3aH0sNw' target="_blank" style='border-right: 1px solid #666; padding-right: 6px;'>Documentation</a></li>
	<?php if ($this->__session->token == null) : ?>
					<li><a href='<?=UIR;?>Login' style='border-right: 1px solid #666; padding-right: 6px;'>Login</a></li>
	<?php else : ?>
					<li>Logged in as <a href='<?=UIR;?>Player/index/<?=$this->__session->user_id; ?>' style='border-right: 1px solid #666; padding-right: 6px;'><?=$this->__session->user_name; ?></a></li>
					<li><button onClick='javascript:window.location.href="<?=UIR;?>Login/logout"' >Logout</button></li>
	<?php endif; ?>
          <li class='search-switch search-switch-on'><a onclick="$('.search-switch').toggle('slow').css('display', 'table-cell');">Search</a></li>
					<li class='search-switch search-switch-off'><input id='PlayerSearch' placeholder="Players" /></li>
					<li class='search-switch search-switch-off'><input id='ParkSearch' placeholder="Parks" /></li>
				</ul>
			</div>
	</div>

	<div id="sidr">
		<!-- Your content -->
		<ul>
				<ul>
          <li><a href='https://www.facebook.com/mORKmobile/posts/2275859462673190'>Get the ORK Mobile!</a></li>
	<?php foreach ($menu as $k => $item) : ?>
					<li><a href='<?=$item["url"] ?>'><?=$item["display"] ?></a></li>
	<?php endforeach; ?>
	<?php if ($this->__session->token == null) : ?>
					<li><a href='<?=UIR;?>Login' style='border-right: 1px solid #666; padding-right: 6px;'>Login</a></li>
	<?php else : ?>
					<li><a href='<?=UIR;?>Player/index/<?=$this->__session->user_id; ?>' style='border-right: 1px solid #666; padding-right: 6px;'><?=$this->__session->user_name; ?></a></li>
					<li><button onClick='javascript:window.location.href="<?=UIR;?>Login/logout"' >Logout</button></li>
	<?php endif; ?>
				</ul>
		</ul>
	</div>

	<script>
		$(document).ready(function() {
			$('#simple-menu').sidr();
		});
	</script>
	
	</body>
</html>
