[pytest]
pythonpath = .
testpaths = tests

[coverage:run]
source =
    lib
    .
omit =
    */tests/*
    tests/*
    */__pycache__/*

[coverage:report]
omit =
    */tests/*
    tests/*
    */__pycache/*
