<?php

// Bump WHATS_NEW_VERSION whenever you add new items — every logged-in user will see
// the modal once on their next page load, then not again until the version changes.
define('WHATS_NEW_VERSION', '2026-07-15');

// Application version — shown in the site footer. Change this if you change the above date.
define('ORK_VERSION', '3.5.4 Walker');

// An array of releases, each with a version, date, and array of items. Each item has an icon (Font Awesome class), title, and body. Make sure the latest
// version matches the ORK_VERSION above, and that the date is in YYYY-MM-DD format and matches the WHATS_NEW_VERSION above.
$WHATS_NEW_ITEMS = [
    ['version' => '3.5.4 Walker', 'date' => '2026-07-15', 'items' => [
        ['icon' => 'fas fa-graduation-cap', 'title' => 'Qualification Tests Arrive', 'body' => 'Kingdoms can now run the Reeve\'s Test and the Corpora Test right inside the ORK. Build your own multiple-choice question banks, set the pass score and how long a pass stays valid, and let players test on their own time with instant auto-grading. A passing score writes straight back into the player\'s official qualifications, so every existing report keeps working — the record-keeping just does itself. Each test type is opt-in per kingdom, so nothing appears until your kingdom turns it on.'],
        ['icon' => 'fas fa-list-ol', 'title' => 'Build and Run Your Own Question Bank', 'body' => 'Test managers get a full dashboard: dial in question count, pass percent, validity window, and retake limits; add questions one at a time or paste a whole batch at once; and pull ready-made questions from a shared library that other kingdoms have opted to publish. You can appoint a subject-matter expert as a test manager without handing over broader officer powers, triage questions players flag as unclear, and reset retakes for a single player or everyone at once.'],
        ['icon' => 'fas fa-user-graduate', 'title' => 'Take the Test on Your Own Time', 'body' => 'From the Qualifications card on your profile, see whether you\'re currently certified, when it expires, and how many retakes you have left — then take the test whenever you\'re ready. Questions come one at a time with the kingdom\'s instructions up top, you can flag anything that looks off without leaving the test, and a passing score sets off a little confetti. Questions can be single-answer or "select all that apply."'],

        // ----- Items flagged notes_only appear on the Release Notes page but NOT in the
        // What's New modal. Order here is the order both surfaces render in. -----
        ['icon' => 'fas fa-check-double', 'title' => 'Select All That Apply', 'notes_only' => true, 'body' => 'A test question can have more than one correct answer. Flip a question to "multiple correct" and the player must pick every right option — scored all-or-nothing, with clear feedback showing exactly which answers they should have chosen. Bulk import spots these for you: star two or more answers in the pasted text and the question is created as multi-answer.'],
        ['icon' => 'fas fa-book-open', 'title' => 'Shared Question Library', 'notes_only' => true, 'body' => 'Kingdoms that opt in share their published questions to a cross-kingdom library, and any kingdom that opts in can copy from them — a running start on building a bank instead of writing every question from scratch. What you import is your own independent copy: reword it, archive it, do as you like, and the kingdom it came from is unaffected. Each question in your bank is badged with the kingdom it came from, and the library shows which edition of the rules each kingdom\'s test is built on, so you can tell how current a question is before you take it.'],
        ['icon' => 'fas fa-flag', 'title' => 'Flag & Triage Questions', 'notes_only' => true, 'body' => 'While taking a test, players can report a question as unclear, incorrect, outdated, or other. Managers see a count on each flagged question and can review the reasons, then edit or clear them — a quick feedback loop for keeping the bank sharp.'],
        ['icon' => 'fas fa-redo', 'title' => 'Retake Controls', 'notes_only' => true, 'body' => 'Set a maximum number of attempts per player (or leave it unlimited), and reset the counter for one player who tripped up or for the whole kingdom after you rewrite a batch of questions.'],
        ['icon' => 'fas fa-exclamation-triangle', 'title' => 'Weather Safety at a Tap', 'body' => 'Extreme-heat and frostbite-risk badges across park, event, and weather pages are now clickable — tap one for a quick safety summary with links to trusted CDC and Health Canada guidance. Weather cards and map popups also show the "feels like" apparent temperature whenever heat index or wind chill pushes it meaningfully away from the plain air reading, so the number matches the weekly rundown.'],
        ['icon' => 'fas fa-qrcode', 'title' => 'Smarter Self Sign-In Picker', 'notes_only' => true, 'body' => 'When you check in by QR code and choose which class to sign in as, each option now shows your current level and how many credits until the next one — like "Warrior · L4 · 5 to L5" — so you can spend the credit where it does the most good.'],
        ['icon' => 'fas fa-calendar-alt', 'title' => 'Calendar Items Keep Their Length', 'notes_only' => true, 'body' => 'Editing a calendar item\'s start date now slides the end date by the same amount, preserving the item\'s duration — moving something a week earlier no longer silently stretches it to eight days. Applies to both Kingdom and Park calendars.'],
        ['icon' => 'fas fa-mobile-alt', 'title' => 'No More Cut-Off Buttons on Mobile', 'notes_only' => true, 'body' => 'On mobile Safari, tall pop-ups like the event editor no longer push their Save / Cancel / Delete buttons below the bottom of the screen when the address bar is showing.'],
    ]],
    ['version' => '3.5.3 Rose', 'date' => '2026-06-14', 'items' => [
        ['icon' => 'fas fa-clipboard-list', 'title' => 'Plan Your Whole Event in One Place', 'body' => 'Event pages are now a full planning workspace. Build a real schedule with categories, locations, and the people leading each activity; add Event Staff and hand them exactly the powers they need — manage details, take attendance, run the schedule, or coordinate feast — without making them park officers. Set admission tiers, link tickets, and track feast menus, costs, dietary notes, and allergens, all right on the event.'],
        ['icon' => 'fas fa-qrcode', 'title' => 'Sign In and Sign Up by QR Code', 'body' => 'Day-of attendance is now a 30-second loop. Generate a Sign-In Link with a QR code — players scan, sign in, and credits are recorded automatically (configurable per link). Brand-new to Amtgard? A Self-Registration QR lets newcomers create their account and check in on the spot, no laptop required.'],
        ['icon' => 'fas fa-image', 'title' => 'Custom Hero Banners Across the ORK', 'body' => 'Player, Park, Kingdom, and Unit profiles can now feature a custom hero banner. Upload your own artwork, drag to frame it just right with safe-zone guidance, and choose whether your heraldry or logo shows over it. Download a sizing template from any banner editor to design the perfect image.'],
        ['icon' => 'fas fa-calendar-week', 'title' => 'A Smarter Calendar', 'body' => 'The rollup calendar gets a major upgrade: add Calendar Items (including kingdom-wide events), flag items as officer-only or locals-only, collect RSVPs, switch to a Map view, and peek at any event with a quick-look popover — no page load. Park days can now recur "every X weeks," and the calendar, weather "playing today," and park lists all understand the new cadence.'],

        // ----- Notes-only items (Release Notes page; not surfaced in the modal) -----
        ['icon' => 'fas fa-copy', 'title' => 'Copy From Past Event', 'notes_only' => true, 'body' => 'Running the same event again? Start from a previous one and bring its schedule, staff, fees, feast, external links, and banner along — then tweak what changed. Available when creating events from both Park and Kingdom pages.'],
        ['icon' => 'fas fa-crown', 'title' => 'Royal Progress at a Glance', 'notes_only' => true, 'body' => 'When the Monarch or Regent of your kingdom or principality has RSVP\'d to an event, you\'ll now see an indicator on the events tab to let you know to expect the monarchy there!'],
        ['icon' => 'fas fa-user-shield', 'title' => 'Granular Event Staff Capabilities', 'notes_only' => true, 'body' => 'Event Staff get additive capability flags — manage, attendance, schedule, and feast — so you can appoint a Feastcrat or Gatecrat without handing over full park-officer rights. Capabilities stack: someone can run the schedule and feast but not touch attendance, exactly as you set it.'],
        ['icon' => 'fas fa-feather-alt', 'title' => 'Feast & Schedule Unified', 'notes_only' => true, 'body' => 'Feast and food are now part of the event schedule, so everything your event runs lives in one place — with a dedicated Feast view that surfaces menus, costs, dietary restrictions, and allergens when you need them.'],
        ['icon' => 'fas fa-utensils', 'title' => 'Dietary Preferences on Your Profile', 'notes_only' => true, 'body' => 'Set your dietary preferences once on your profile and they become available to feast planners — making it easier for events to cook for everyone.'],
        ['icon' => 'fas fa-th', 'title' => 'Schedule Grid View & Editing Polish', 'notes_only' => true, 'body' => 'Switch the event schedule between a list and an at-a-glance grid view, with a 5-minute time picker, save-and-continue / save-and-close modes, and dirty-tracking that won\'t let you lose unsaved changes.'],
        ['icon' => 'fas fa-magic', 'title' => 'Help Me Write Your Event Description', 'notes_only' => true, 'body' => 'A new "Help Me Write…" starter gives you a head start on your event description so you\'re never staring at a blank box.'],
        ['icon' => 'fas fa-ticket-alt', 'title' => 'Ticket Links', 'notes_only' => true, 'body' => 'Add a label and URL for ticket sales and it surfaces right in the event\'s Fees card.'],
        ['icon' => 'fas fa-external-link-alt', 'title' => 'Event External Links', 'notes_only' => true, 'body' => 'Attach external links — registration, rules, Discord, and more — directly to your event.'],
        ['icon' => 'fas fa-calendar-plus', 'title' => 'More Event Types', 'notes_only' => true, 'body' => 'New event-type options including Day Event and Park Raid, plus typed royal occasions that drive the new crown icons on the Kingdom events tab.'],
        ['icon' => 'fas fa-link', 'title' => 'Copy Event Share Link', 'notes_only' => true, 'body' => 'Grab a shareable link to any event with a single click.'],
        ['icon' => 'fas fa-clock', 'title' => 'RSVP Date Gating & Schedule Times', 'notes_only' => true, 'body' => 'RSVP controls respect event timing, and schedule item times are stored as real dates so they stay put — editing the event date no longer shuffles your agenda.'],
        ['icon' => 'fas fa-id-badge', 'title' => 'Persona Name Shadow Toggle', 'notes_only' => true, 'body' => 'A standalone toggle to add or remove the drop shadow on your persona hero header, for exactly the look you want.'],
        ['icon' => 'fas fa-download', 'title' => 'Banner Sizing Templates', 'notes_only' => true, 'body' => 'Every banner editor — event, player, park, kingdom, and unit — now offers a downloadable PNG template so you can design artwork at the right dimensions before uploading.'],
        ['icon' => 'fas fa-moon', 'title' => 'Dark Mode Polish', 'notes_only' => true, 'body' => 'Extensive dark-mode contrast passes across event detail, calendar items, sign-in and self-registration flows, banners, tooltips, royal crowns, copy-link, and event search.'],
        ['icon' => 'fas fa-tools', 'title' => 'Performance, Polish & Bug Fixes', 'notes_only' => true, 'body' => 'A long list of stability, performance, and UX fixes across event management, banners, the calendar, copy-from-past-event, and sign-in flows — including RSVP/coordinator query batching, faster kingdom-calendar royal lookups, park-day recurrence validation, copy-event validation feedback, mobile layout, and dark-mode contrast.'],
    ]],
    ['version' => '3.5.2 Mask', 'date' => '2026-05-13', 'items' => [
        ['icon' => 'fas fa-feather-alt', 'title' => 'Tell Your Amtgard Story', 'body' => 'The new Design My Profile customizer lets you make your profile feel like yours — markdown bio with Quick Add snippets, adding color and font flair to your nameplate, a flexible name builder with title pickers, beltline visibility, pronunciation guides, and viewer font preferences (including Lexend for dyslexia). Then add your own knightings, first wins, retirements, and any moments worth remembering to a personal Milestones timeline on your About tab.'],
        ['icon' => 'fas fa-thumbs-up', 'title' => 'Recommendation Upgrades', 'body' => 'See an award recommendation you agree with? Hit the + button to add your support — optionally with a few words on why. Already filed a recommendation but learned something new about the recipient? You can now edit your own reason text from any Player, Park, or Kingdom profile where you spotted the rec.'],
        ['icon' => 'fas fa-medal', 'title' => 'Custom Title Aliases', 'body' => 'If you were given an award such as Lord, Countess, or Knight, but received it with a custom alias like Mentor, Archon, or Jarl which was put in as a custom title, your Monarchy can now edit the custom title and link it to the standard award so it shows in reports such as the Beltline Explorer.'],
        ['icon' => 'fas fa-cogs', 'title' => 'Improved Performance and Administration', 'body' => 'Player profile pages now paint fast and lazy-load their heavier sections; big kingdom rosters load in year buckets with smart lazy paint. Officers can merge duplicate players at the park level, the audit log now covers player creation and park edits, and scoped Park/Kingdom Admin grants stay scoped (they no longer escalate to global access). Plus performance indexes and cache wins across attendance, awards, units, and search.'],

        // ----- Notes-only items (Release Notes page; not surfaced in the modal) -----
        ['icon' => 'fas fa-shield-alt', 'title' => 'Knights Can Choose Belt Display', 'notes_only' => true, 'body' => 'Belted Knights get a new Icons tab in Design My Profile with three options: the generic white belt (default), their actual knighthood belts shown in award-date order, or no belt at all.'],
        ['icon' => 'fas fa-filter', 'title' => 'Profile Content Guardrails', 'notes_only' => true, 'body' => 'To help ensure Amtgard remains a safe and positive place for all players, certain text entry fields such as Persona name, title, the Mask About Me sections, etc. have added a content filter to ensure profanity and offensive terminology may not be entered. Please note, the content filter may be overly sensitive to begin with. Report any issues with legitimate, non-offensive terminology to ORK Feedback and the term may be allowlisted.'],
        ['icon' => 'fas fa-users-cog', 'title' => 'Officer & Admin Improvements', 'notes_only' => true, 'body' => 'Park-level player merge for duplicate cleanup; audit-log coverage expanded to player creation and park mutations; scoped Park/Kingdom Admin grants stay strictly scoped (with banner badges showing exactly which scopes a player carries); officers now sort by canonical hierarchy across all profile views.'],
        ['icon' => 'fas fa-tachometer-alt', 'title' => 'Performance Tuning', 'notes_only' => true, 'body' => 'Roster pages paint in year buckets with content-visibility lazy paint; performance indexes on attendance, awards, units, and mundane queries; cache TTL bumps and targeted cache busting on player classes, recommendations, and event search.'],
        ['icon' => 'fas fa-tools', 'title' => 'Polish & Bug Fixes', 'notes_only' => true, 'body' => 'Updated to Open Sans font for better readability site-wide; share button on event detail pages; dark-mode contrast fixes on hero overlay, scope notes, and color/privacy labels; ladder counting accuracy with ladder/peerage validation; design modal sizing and hex input refinement; milestone sort order; account/qualifications save error surfacing; and a long list of smaller fixes throughout.'],
        ['icon' => 'fas fa-feather', 'title' => 'Quick Add Snippets + About-tab Edit Pencil', 'notes_only' => true, 'body' => 'Drop pre-built sections into your About bio with one click, and jump straight to editing from a pencil icon on the About tab itself.'],
        ['icon' => 'fas fa-font', 'title' => 'Basic & Dyslexia-Friendly Fonts', 'notes_only' => true, 'body' => 'New viewer preferences let you enforce basic fonts site-wide for legibility, or switch to Lexend — a typeface designed to improve reading proficiency for people with dyslexia.'],
        ['icon' => 'fas fa-microphone', 'title' => 'Pronunciation Guide + Persona Privacy', 'notes_only' => true, 'body' => 'Tell the world how to say your persona name, and choose who can see your real name and email — defaults match the existing privacy posture (always visible to monarchy and admins).'],
        ['icon' => 'fas fa-eye', 'title' => 'About-tab Visibility Banner', 'notes_only' => true, 'body' => 'A banner at the top of the About design tab makes it obvious whether what you\'re writing is private, restricted, or visible to everyone.'],
        ['icon' => 'fas fa-sticky-note', 'title' => 'Notes Tab — Visibility & Self-Service Close-out', 'notes_only' => true, 'body' => 'Player Notes are now restricted to those who should see them, with an in-context infobox and the ability to close out your own follow-ups without bothering an officer.'],
        ['icon' => 'fas fa-history', 'title' => 'Reactivate Revoked Awards & Titles', 'notes_only' => true, 'body' => 'Revoked an award or title in error? You can now bring it back without re-creating the record from scratch.'],
        ['icon' => 'fas fa-search', 'title' => 'Mundane Name Search on Players Tab', 'notes_only' => true, 'body' => 'Search your kingdom\'s Players tab by mundane name — with the same restricted-flag honoring as the rest of the system.'],
        ['icon' => 'fab fa-discord', 'title' => 'Discord Link in Resources', 'notes_only' => true, 'body' => 'Logged-in users now get a quick link to the Amtgard ORK Discord under the Resources dropdown.'],
        ['icon' => 'fas fa-map-marker-alt', 'title' => 'Park Abbreviation in Events to Check Out', 'notes_only' => true, 'body' => 'The "Events to Check Out" widget now shows park abbreviations so you can tell at a glance which kingdom each event is in.'],
        ['icon' => 'fas fa-sign-in-alt', 'title' => 'Login Preserves Where You Were Going', 'notes_only' => true, 'body' => 'Get bumped to the login screen by a stale session? After signing in you\'ll land on the page you were trying to reach, not the dashboard.'],
    ]],
    ['version' => '3.5.1 Owl', 'date' => '2026-04-18', 'items' => [
        ['icon' => 'fas fa-moon', 'title' => 'Dark Mode', 'body' => 'The ORK now supports dark mode! The theme toggle has three modes — click to cycle: Auto (half-circle icon — follows your OS setting) → Dark (moon) → Light (sun). Your preference is saved automatically.'],
        ['icon' => 'fas fa-desktop', 'title' => 'Follows Your System', 'body' => 'If you leave the theme set to automatic, the ORK will follow your device\'s light or dark preference and update instantly when it changes.'],
        ['icon' => 'fas fa-paint-brush', 'title' => 'Full Coverage', 'body' => 'Dark mode is supported across player, kingdom, and park profiles, as well as the navigation, modals, tables, calendars, and all other site components.'],
        ['icon' => 'fas fa-magic', 'title' => 'Quality of Life Updates', 'body' => 'Several quality of life updates to award entry and Event RSVPs — see the release notes for details.'],
        ['icon' => 'fas fa-trophy', 'title' => 'Smarter Award Entry', 'notes_only' => true, 'body' => 'Granting awards just got tidier. The Player, Kingdom, and Park award modals now have dedicated buttons for Achievement Titles (Knighthoods, Masterhoods, Paragons, Noble Titles) and Associations (Associate Titles) — no more scrolling through a giant list. Pick the bucket, pick the award, done.'],
        ['icon' => 'fas fa-list-ol', 'title' => 'Ladder Tally Improvement', 'notes_only' => true, 'body' => 'If a player had duplicate ranked entries (say, two Crown 3s), we now only count one of those toward the "count of awards or highest databased rank, whichever is higher" calculation.'],
        ['icon' => 'fas fa-clipboard-check', 'title' => 'Event RSVP Tab — Now With Superpowers', 'notes_only' => true, 'body' => 'New Sign-in Credits field right in the RSVP table so you can set credits before the event even starts (it syncs with quick check-in too). Kingdom and Park are now their own clickable columns, and a brand new "Waivered?" column shows at a glance who\'s got a waiver on file — be sure to check your kingdom/park/event policies on active waivers vs event-specific waivers being needed.'],
        ['icon' => 'fas fa-keyboard', 'title' => 'Typo-Catching Email Field', 'notes_only' => true, 'body' => 'Type gmial.com by mistake? The system now gently asks "Did you mean gmail.com?" with a one-click fix. Works on the Add Player popup and your Edit Account screen.'],
        ['icon' => 'fas fa-at', 'title' => 'Email Reminder for Players Without One', 'notes_only' => true, 'body' => 'If you log in and don\'t have a recovery email on file, you\'ll get a friendly nudge to add one. (Don\'t want to deal with it right now? "Skip for now" and take care of it next time.)'],
    ]],
    ['version' => '3.5.0 Dragon', 'date' => '2026-04-02', 'items' => [
        ['icon' => 'fas fa-user', 'title' => 'New Player Profiles', 'body' => 'Player profiles have a fresh new look with stats, awards, titles, attendance, and more all in one place.'],
        ['icon' => 'fas fa-chess-rook', 'title' => 'New Kingdom Profiles', 'body' => 'Kingdom pages now show parks, events, tournaments, a live map, and reports in a redesigned layout.'],
        ['icon' => 'fas fa-tree', 'title' => 'New Park Profiles', 'body' => 'Park pages now show your weekly schedule, upcoming events, tournaments, and reports at a glance. Taking attendance is now faster with recent sign-ins displayed for Quick Add.'],
        ['icon' => 'fas fa-calendar-check', 'title' => 'Event Enhancements', 'body' => 'See all upcoming events and park days in a rollup calendar, create events with no templates required, and RSVP to events you want to attend to speed up check-in.'],
        ['icon' => 'fas fa-cog', 'title' => 'Managing the ORK', 'body' => 'Updating your profile, parks, and kingdoms is easier than ever. Look for the gear and edit symbols to make changes directly on the page.'],
        ['icon' => 'fas fa-gift', 'title' => 'And so much more!', 'body' => 'So many improvements, bug fixes, and quality-of-life changes across the entire ORK with this first of many upcoming updates.']
    ]]
    // Add future items above this line; bump WHATS_NEW_VERSION date to re-show for all users. Change ORK_VERSION when you want to update the version shown in the footer.
];
