-- ORK3 Test Database Extract
-- source: mirror
-- table: ork_parktitle
-- rows: 168

INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (1, 1, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (2, 1, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (3, 1, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (4, 1, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (5, 1, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (12, 3, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (13, 3, 'Barony', 30, 20, 12, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (14, 3, 'Duchy', 40, 40, 25, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (17, 4, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (18, 4, 'Barony', 30, 20, 20, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (19, 4, 'Duchy', 40, 40, 40, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (21, 5, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (22, 5, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (23, 5, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (24, 5, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (25, 5, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (27, 6, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (28, 6, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (29, 6, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (31, 7, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (32, 7, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (33, 7, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (34, 7, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (35, 7, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (36, 8, 'Freehold', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (41, 9, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (42, 9, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (43, 9, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (44, 9, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (45, 9, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (46, 10, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (47, 10, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (48, 10, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (49, 10, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (50, 10, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (51, 11, 'Shire', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (52, 11, 'Barony', 20, 11, 5, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (53, 11, 'County', 30, 21, 11, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (54, 11, 'Duchy', 40, 31, 31, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (55, 11, 'Grand Duchy', 60, 41, 41, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (56, 12, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (57, 12, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (58, 12, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (59, 12, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (60, 12, 'Kingdom', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (61, 13, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (62, 13, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (63, 13, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (64, 13, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (65, 13, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (66, 14, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (67, 14, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (68, 14, 'Barony', 30, 15, 12, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (69, 14, 'Duchy', 40, 30, 26, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (70, 14, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (71, 15, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (72, 15, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (73, 15, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (74, 15, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (75, 15, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (77, 16, 'Shire', 1, 1, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (78, 16, 'Barony', 20, 20, 15, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (79, 16, 'Duchy', 40, 40, 30, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (80, 16, 'Grand Duchy', 75, 75, 60, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (82, 17, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (83, 17, 'Barony', 30, 20, 15, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (84, 17, 'Duchy', 40, 40, 35, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (85, 17, 'Grand Duchy', 50, 60, 55, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (87, 18, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (88, 18, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (89, 18, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (92, 19, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (93, 19, 'Barony', 30, 15, 20, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (94, 19, 'Duchy', 40, 30, 40, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (97, 20, 'Shire', 20, 5, 3, 'week', 26);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (98, 20, 'Barony', 30, 20, 15, 'week', 26);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (99, 20, 'Duchy', 40, 30, 25, 'week', 26);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (101, 21, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (102, 21, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (103, 21, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (104, 21, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (105, 21, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (107, 22, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (108, 22, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (109, 22, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (111, 23, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (112, 23, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (113, 23, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (114, 23, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (115, 23, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (117, 24, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (118, 24, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (119, 24, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (120, 24, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (121, 25, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (122, 25, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (123, 25, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (124, 25, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (125, 25, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (126, 26, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (127, 26, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (128, 26, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (129, 26, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (130, 26, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (131, 27, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (132, 27, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (133, 27, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (134, 27, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (135, 27, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (136, 28, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (137, 28, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (138, 28, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (139, 28, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (140, 28, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (141, 29, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (142, 29, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (143, 29, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (144, 29, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (145, 29, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (146, 30, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (147, 30, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (148, 30, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (149, 30, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (150, 30, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (152, 31, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (153, 31, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (154, 31, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (156, 32, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (157, 32, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (158, 32, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (159, 32, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (160, 32, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (161, 33, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (162, 33, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (163, 33, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (164, 33, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (165, 33, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (166, 34, 'Burg', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (167, 34, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (168, 34, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (169, 34, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (170, 34, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (171, 35, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (172, 35, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (173, 35, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (174, 35, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (175, 35, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (176, 36, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (177, 36, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (178, 36, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (179, 36, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (180, 36, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (181, 38, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (182, 38, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (183, 38, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (184, 38, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (185, 38, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (186, 25, 'Inactive ', 0, 0, 0, 'month', 0);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (187, 39, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (188, 39, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (189, 39, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (190, 39, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (191, 39, 'Grand Duchy', 50, 60, 56, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (192, 40, 'Outpost', 10, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (193, 40, 'Shire', 20, 5, 1, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (194, 40, 'Barony', 30, 15, 13, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (195, 40, 'Duchy', 40, 30, 28, 'month', 6);
INSERT INTO `ork_parktitle` (`parktitle_id`, `kingdom_id`, `title`, `class`, `minimumattendance`, `minimumcutoff`, `period`, `period_length`) VALUES (196, 40, 'Grand Duchy', 50, 60, 56, 'month', 6);
